### PR TITLE
updated environment sdk

### PR DESCRIPTION
**Pull request by MrBoOodY**

### CODE REVIEW

**Comment by Abdelazeem777** [comment]
Hi, @MrBoOodY @AbdullahBasuony 

Thanks for the PR.
But could you please explain why do we need to update the Dart SDK version?

Because this update will enforce the users to update as well there projects to the same Dart and this is not applicable to all projects (especially the old ones)

That's why I think postpone this step would be better for the package

**Comment by MrBoOodY** [comment]
The new Dart SDK users can't use this package so if someone has old Dart SDK version he can use the old package version.

**Comment by Abdelazeem777** [comment]
Okay let me check and see if there is a better solution for this issue

**Comment by Abdelazeem777** [comment]
After checking the current version of requests_inspector with the latest flutter version

Everything is working fine except Hasura because it depends on an old version of http: 0.13.0

so based on this [issue](https://github.com/Flutterando/hasura_connect/issues/133) on Hasura

I am going to wait till they update their dependency to the latest version of http

But for now, you can just override the Hasura http version by adding the following the `pubspec.yaml` file

```yml
dependency_overrides:
  http: ^1.1.0
```

and everything will work fine after that 

I will keep this issue open till Hasura makes its update

**Comment by MrBoOodY** [comment]
They will not update it because they already left it for a while.
You can see the last commits for the package.
But can fork hasoura and edit it right?

**Comment by Abdelazeem777** [comment]
Unfortunately, I already tried the fork solution but it didn't work because it's a package not a normal project

**Comment by Abdelazeem777** [comment]
`hasura_connect` support is completely removed from the package until they fix the package conflicts.

I am closing this PR and please check the new version `v3.3.0`
So, thanks for your support and contribution

Very appreciated 🙏🙏

**Pull request closed without merging**
